# Generated by Django 5.2 on 2025-04-23 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='My First Post', max_length=100),
            preserve_default=False,
        ),
    ]
